languaje: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: netfily
  skip-cleanup: true
  keep-history: true
  auth: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXSBKIuPEvRMyalOkvoCDCH2vPnUxpOXv/MKUNTXvd0hiukG9jzKyJa1VlRVODIDdljWTk0RDqjMF2dk5lUBgCcQaZuJq/Gtzj/cBQzUonlK464BdO1Duskqolab18sFSgnUQc5K2BoxbB6Y9av+6ezHqVGfqPr/wi0eDtQPDVTzDJV5mMDLLJFpW1B8Dw2di7u2pSfgQiI5fjQ/xCGAhqD/CgREO1vh/lSuhlA5tIdxlzr2r6j4jVGJCYliQNyPOr7H392lWh+LV1d3hITPEHjknNyoHDxmfpxJVqZq5SrTMmnXzyn1pgGl+e4Mf4RptN1fbateflQQR9uRxom96bxKQzgJ+OTIQiXxsz54vBO83Pi7p48ParNqDLKa0XP95zumQYg80Nbh+1P/dpfrH4npUqN2QsfNwYDHHBrqH271u0TOa5oiOoatAEHdH1vloxvQ4koVSO/HX6eK9gxLvndh9cIerDkhebR5tM5us1889ftAzk5JKgtFG7Uy6bXGcIUiF1DtoZ4hYbt5TRzIAinbMLIAcNn8t3qA7lBMMQzLr+tjqGtmmpmf21mOoLzyWZEAQox6/rrBnXuocb4eDG2FjwtDDtrGiRPzqRSUaGVI3xFgZyPHkTS1eHjaAcWO68cOymQjhV5YwEMGSF9t4cn4r7+386FExnPh/tDEeT2Q==
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "deploy del proyecto"
  edge: true
  site: "hola"
  on:
    branch: main